name: Main

on: [ push ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1.x

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: |
        ./build.sh

    - name: Test
      run: |
        ./test.sh
